### ISSUE TITLE
Respuesta a tus preguntas y explicación de concepto

### ISSUE THREAD

**Issue by gaal1le0** [DanBaDo/ExcuseGenerator#1]
https://github.com/DanBaDo/ExcuseGenerator/blob/55bf2273c3f21be8917ad1dcf01e57107074cf9d/index.js#L50

## Detalle importante

Primero que nada, tu proyecto me parece **increíble**, has usado diferentes cosas lo que demuestra que tienes un dominio en la programación funcional, sin embargo hay una cosa que me encantaría decirte bajo mi criterio.

En este caso, en la función countLetters yo no aplicaría recursividad ya que no hay ninguna profundidad, recuerda la frase: **Solución en tiempo y forma para el problema**. Si te fijas el coste algoritmo de la funcion es O(n) para el primer for pero cuando empezamos con recursividad sería como elevar esa n al cuadrado teniendo como total O(n2). Entonces por más que apliques recursividad aquí no vas a reducir el coste algoritmíco, por lo que to evitaría usar aquí recursividad, en JS hay que tener cuidado. Yo usuaría la siguiente solución:

```js

// contar el numero de repeticiones de letra en un array
function countLetterMatches(array) {

    let response = {};

    // limpiamos el array
    const cleanData = cleanArray(array);

    // recorremos el array
    for (let item of cleanData) {

        // recorremos cada letra dal item
        for (let letter of item) {

            // comprobamos si existe
            if (response.hasOwnProperty(letter.toLowerCase())) {
                // aumentamos el contador de repeticioines
                response[letter.toLowerCase()]++;
            } else {
                // creamos una nueva propiedad
                response[letter.toLowerCase()] = 1;
            }

        }

    }

    return response;

}

```

Más adelante en clase o en el coding-weekend explicaré el motivo para evitar recursividad aquí.

## Respuesta a tus preguntas

- ¿Empleo bien el término iteración en countLetters? ¿debería de hablar de instancias?

No comprendo tu pregunta, a que te refieres, si puedes indicarme la linea donde mencionas esa palabra ya que he visto varias referencias a esa palabra y no se por cual me preguntas.

- ¿Donde encuentro información sobre operaciones seguras para programación asyncrona en JS? No tengo claro si esta forma de trabajo sería segura en una implementación asíncrona de la función countLetters.

Yo no metería la función countLetters en programación asíncrona, porque podrías perder el control de la aplicación si escalases ya que podría verse afectada, ten en cuenta que puede petarte. La programación asincrona tiene una buena buena utilidad cuando se hacen llamada a servicios de backend como REST/SOAP pero eso lo veremos más adelante. Por ahora no te centres en las operaciones asincronas, miralas como si fueran sincronas hasta que avancemos más en JS.

- Creo que existe una forma normalizada de documentar las funciones. ¿Podrías recomendarme alguna lectura al respecto?.

Normalmente se instala un plugin en **VSCode** que te permite dale colores a los siguientes formatos, te recomiendo seguir el siguiente modelo.
Normalmente se usa esa estructura, documentando un overview del concepto general de la función, el autor (para los reviews de los pull-request en el equipo), la version y una documentación sobre parámetros y valores de retorno, en este caso al ser un lenguaje que tiene **tipado dinámico** no tiene mucho sentido pero normalmente se usa TS para evitar errores y ahí si es mas común documentar el tipo.

[Mira aquí](https://javalangnullpointer.wordpress.com/2007/02/14/documentar-el-codigo-javascript/)

```js

/**
* @fileoverview Libreria con funciones de utilidad
*
* @author example
* @version 1.0
*/
/**
* Muestra un mensaje de texto
* @param {String} metodo nombre del metodo
* @param {String} mensaje mensaje a mostrar
* @returns {integer} el codigo de retorno 0
*/
function trazas(metodo,mensaje){
alert("["+metodo+"]:"+mensaje);
return 0;
}
//--------

```

**Comment by DanBaDo** [comment]
Lo de "iteración" lo empleo en el Readme.md.
Tampoco tiene mayor importancia.
Ok a lo de la función recursiva y a lo de hacerla asincrona.
Lo que me tiraba para atras de hacerlo asincrono (no lo voy a hacer y para un array plano de 5 elementos no tiene sentido) es que no se si el operador ++ y -- actuando sobre propiedades de un objeto son seguras a este nivel o pueden presentar problemas en un acceso simultaneo de varias instancias de la función. Tampoco se si realmente esta programación asincrona de JS se comporta como hilos o es un poco más de juguete y realmente no hay una ejecución simultanea de código.
Hay muchas cosas que aprender, pero cada cosa a su tiempo.
Gracias por tus respuestas.

**Comment by gaal1le0** [comment]
Recuerdo que te dije yo el tema de la recursividad!!! JJAJAJA
En JS no existen hilos, es una pajotada que simula la operación multihilo, se hace asignando una operacion detras de otra y no empezando la siguiente hasta que acaba la anterior. Realmente no hay ejecución simultanea aprovechando el hilo. Eso se puede hacer en lenguajes más avanzados.
Tienes que tener en cuenta que los hilos (son virtualizaciones) y pueden ser diferentes a los hilos fisicos. 

Más adelante en el coding-wekend (por que no es temario del curso) explicare más sobre desarollo multihilo

**Comment by DanBaDo** [comment]
👍
